version: '3.3'
services:
    mysql:
        image: mysql:5.7
        container_name: your_container_name
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "33060:3306"
        expose:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: 
            MYSQL_DATABASE: 
            MYSQL_USER: 
            MYSQL_PASSWORD: 
        volumes:
            - schemas:/var/lib/mysql
        networks:
            mysql_host:
                aliases:
                    - mysql_net
networks:
    mysql_host:
        driver: bridge
volumes:
    schemas:
